# Generated by Django 3.0.6 on 2020-06-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200613_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='clothing_size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shoe_size',
            field=models.CharField(blank=True, choices=[('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45')], max_length=200, null=True),
        ),
    ]
